/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventana;

/**
 *
 * @author Marlon
 */
public class Interfaz_Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Interfaz_Inicio
     */
    public Interfaz_Inicio() {
        initComponents();
    
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSalir = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextField1Usuario = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonSeccion = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 102));
        jButtonSalir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imajenes/logo uni.png"))); // NOI18N
        jLabelIcono.setText("jLabel1");
        add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 220, 160));

        jLabelUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Contraseña:");
        add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jTextField1Usuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextField1Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1UsuarioActionPerformed(evt);
            }
        });
        add(jTextField1Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, 30));

        jPasswordField1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 170, 30));

        jButtonSeccion.setBackground(new java.awt.Color(51, 0, 102));
        jButtonSeccion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButtonSeccion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeccion.setText("INICIAR");
        jButtonSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeccionActionPerformed(evt);
            }
        });
        add(jButtonSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imajenes/ec72ca3f84a7f6d1fa09d6a3861cd9f0.jpg"))); // NOI18N
        jLabelFondo.setText("fondo");
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 378, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
       //Fubciones del boton de Salir 
       System.exit(0);
       
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextField1UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1UsuarioActionPerformed

    private void jButtonSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSeccion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1Usuario;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
